language: java
jdk:
  - oraclejdk8
env:
  global:
    - GRADLE_OPTS="-Xms128m"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libboost-dev libboost-test-dev libboost-program-options-dev libevent-dev automake libtool flex bison pkg-config g++ libssl-dev
  - wget http://www.us.apache.org/dist/thrift/0.9.3/thrift-0.9.3.tar.gz
  - tar xfz thrift-0.9.3.tar.gz
  - cd thrift-0.9.3 && ./configure --without-ruby && sudo make install && cd ../

notifications:
  email:
    - arvind.kandhare@dell.com
    - ram.viswanathan@dell.com
    - tom.kaitchuck@dell.com
    - andrei.paduriou@dell.com
    - shivesh.ranjan@dell.com
    - bhargav.gulavani@dell.com
    - sandeep.shridhar@dell.com
    - Vijayalakshmi.Veerubhotla@emc.com
    - Abhijeet.Jadhav@emc.com

