language: java
jdk:
  - oraclejdk8
env:
  global:
    - GRADLE_OPTS="-Xms128m"

sudo: required

services:
  - docker

notifications:
  email:
    - arvind.kandhare@dell.com
    - ram.viswanathan@dell.com
    - tom.kaitchuck@dell.com
    - andrei.paduriou@dell.com
    - shivesh.ranjan@dell.com
    - bhargav.gulavani@dell.com
    - sandeep.shridhar@dell.com
    - Vijayalakshmi.Veerubhotla@emc.com
    - Abhijeet.Jadhav@emc.com

